application: httpdump
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: myproject.wsgi.application

libraries:
- name: django
  version: "1.5"
- name: django-debug-toolbar
  version: "1.3.2"
